In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/data/processed/dataset.parquet')

In [3]:
df

,sex,age_years,albumin,blood_urea_nitrogen,creatinine,uric_acid,hba1c_percent,total_cholesterol,hdl_cholesterol,triglycerides,...,red_cell_distribution_width,platelet_count,calcium,sodium_si,potassium_si,phosphorus,total_bilirubin,total_protein,globulin,ggt_si
0,1.0,22.0,4.8,14.0,0.91,4.9,5.1,168.0,41.0,87.0,...,11.8,223.0,9.6,137.0,3.9,3.3,0.6,7.6,2.8,14.0
1,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.4,259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,14.0,4.0,16.0,0.65,5.8,5.5,158.0,44.0,64.0,...,12.6,259.0,9.1,137.0,3.8,5.0,0.4,7.0,3.0,8.0
3,2.0,44.0,3.7,5.0,0.89,4.5,4.9,196.0,28.0,71.0,...,14.1,297.0,9.2,138.0,4.3,3.2,0.3,6.0,2.3,18.0
4,2.0,14.0,4.1,12.0,0.50,5.8,5.9,165.0,63.0,87.0,...,12.9,257.0,9.7,139.0,4.0,4.3,0.5,6.9,2.8,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36987,2.0,67.0,3.7,12.0,0.48,2.9,6.6,203.0,60.0,81.0,...,13.9,238.0,8.8,139.0,3.5,3.0,0.5,7.4,3.7,56.0
36988,1.0,40.0,3.9,9.0,0.98,5.9,5.9,241.0,50.0,96.0,...,14.7,203.0,8.8,140.0,3.6,3.1,0.2,7.4,3.5,25.0
36989,2.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,64.0,NaN,...,13.9,305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36990,1.0,63.0,3.6,13.0,0.93,6.0,5.9,157.0,44.0,116.0,...,14.7,194.0,8.6,142.0,3.9,2.4,0.6,6.7,3.1,18.0
36991,1.0,74.0,3.8,20.0,0.97,5.6,5.7,173.0,65.0,94.0,...,13.6,160.0,9.2,145.0,4.3,3.0,0.5,6.9,3.1,20.0

In [4]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sex                          36992 non-null  float64
 1   age_years                    36992 non-null  float64
 2   albumin                      28262 non-null  float64
 3   blood_urea_nitrogen          28256 non-null  float64
 4   creatinine                   28259 non-null  float64
 5   uric_acid                    28252 non-null  float64
 6   hba1c_percent                28851 non-null  float64
 7   total_cholesterol            28254 non-null  float64
 8   hdl_cholesterol              32697 non-null  float64
 9   triglycerides                28259 non-null  float64
 10  white_blood_cell_count       36770 non-null  float64
 11  lymphocyte_percent           36730 non-null  float64
 12  monocyte_percent             36730 non-null  float64
 13  neutrophil_percent           36730 non-null  float64
 14  red_blood_cell_count         36770 non-null  float64
 15  hemoglobin                   36770 non-null  float64
 16  hematocrit                   36770 non-null  float64
 17  mean_corpuscular_volume      36770 non-null  float64
 18  red_cell_distribution_width  36770 non-null  float64
 19  platelet_count               36769 non-null  float64
 20  calcium                      28215 non-null  float64
 21  sodium_si                    28260 non-null  float64
 22  potassium_si                 28248 non-null  float64
 23  phosphorus                   28257 non-null  float64
 24  total_bilirubin              28220 non-null  float64
 25  total_protein                28237 non-null  float64
 26  globulin                     28236 non-null  float64
 27  ggt_si                       28255 non-null  float64
dtypes: float64(28)
memory usage: 7.9 MB

(36992, 28)

In [5]:
df.describe()

,sex,age_years,albumin,blood_urea_nitrogen,creatinine,uric_acid,hba1c_percent,total_cholesterol,hdl_cholesterol,triglycerides,...,red_cell_distribution_width,platelet_count,calcium,sodium_si,potassium_si,phosphorus,total_bilirubin,total_protein,globulin,ggt_si
count,36992.000000,36992.000000,28262.000000,28256.000000,28259.000000,28252.000000,28851.000000,28254.000000,32697.000000,28259.000000,...,36770.000000,36769.000000,28215.000000,28260.000000,28248.000000,28257.000000,28220.000000,28237.000000,28236.000000,28255.000000
mean,1.505569,35.686175,4.234576,13.632963,0.871370,5.346935,5.719656,183.827281,53.412301,101.204643,...,13.560821,255.917430,9.386454,139.629512,4.016339,3.790550,0.573819,7.167188,2.932660,27.192001
std,0.499976,24.004774,0.365526,5.846568,0.452541,1.429128,1.061741,41.993776,15.232495,37.558653,...,1.313284,69.007234,0.371755,2.450205,0.353310,0.628013,0.308471,0.462675,0.455298,43.167058
min,1.000000,1.000000,2.000000,1.000000,0.160000,0.400000,2.800000,6.000000,5.000000,19.000000,...,10.800000,8.000000,6.400000,102.000000,2.300000,1.000000,0.010000,4.400000,0.600000,2.000000
25%,1.000000,14.000000,4.000000,10.000000,0.680000,4.300000,5.200000,154.000000,43.000000,85.000000,...,12.800000,209.000000,9.100000,138.000000,3.800000,3.400000,0.400000,6.900000,2.600000,13.000000
50%,2.000000,33.000000,4.200000,13.000000,0.820000,5.200000,5.500000,180.000000,51.000000,92.000000,...,13.300000,248.000000,9.400000,140.000000,4.000000,3.800000,0.500000,7.200000,2.900000,18.000000
75%,2.000000,56.000000,4.500000,16.000000,0.980000,6.200000,5.800000,209.000000,62.000000,102.000000,...,14.000000,295.000000,9.600000,141.000000,4.200000,4.200000,0.700000,7.500000,3.200000,28.000000
max,2.000000,80.000000,5.600000,96.000000,17.410000,18.000000,17.800000,639.000000,226.000000,626.000000,...,36.500000,1021.000000,14.800000,161.000000,7.300000,10.900000,7.100000,10.200000,7.000000,2394.000000

In [6]:
df.isna().mean().sort_values()

sex                            0.000000
age_years                      0.000000
red_cell_distribution_width    0.006001
mean_corpuscular_volume        0.006001
hematocrit                     0.006001
hemoglobin                     0.006001
red_blood_cell_count           0.006001
white_blood_cell_count         0.006001
platelet_count                 0.006028
monocyte_percent               0.007083
lymphocyte_percent             0.007083
neutrophil_percent             0.007083
hdl_cholesterol                0.116106
hba1c_percent                  0.220075
albumin                        0.235997
sodium_si                      0.236051
creatinine                     0.236078
triglycerides                  0.236078
phosphorus                     0.236132
blood_urea_nitrogen            0.236159
ggt_si                         0.236186
total_cholesterol              0.236213
uric_acid                      0.236267
potassium_si                   0.236375
total_protein                  0.236673
globulin                       0.236700
total_bilirubin                0.237132
calcium                        0.237268
dtype: float64

In [7]:
df['age_years'].isna().sum()

np.int64(0)

In [8]:
df.select_dtypes(include=["object", "string"]).columns

Index([], dtype='str')

In [9]:
numeric_cols = df.select_dtypes(include="number").columns

df[numeric_cols] = df[numeric_cols].mask(
    df[numeric_cols].abs() < 1e-10
)

In [10]:
df["age_years"].describe()

count    36992.000000
mean        35.686175
std         24.004774
min          1.000000
25%         14.000000
50%         33.000000
75%         56.000000
max         80.000000
Name: age_years, dtype: float64

In [11]:
df.isna().mean().sort_values(ascending=False)

calcium                        0.237268
total_bilirubin                0.237132
globulin                       0.236700
total_protein                  0.236673
potassium_si                   0.236375
uric_acid                      0.236267
total_cholesterol              0.236213
ggt_si                         0.236186
blood_urea_nitrogen            0.236159
phosphorus                     0.236132
triglycerides                  0.236078
creatinine                     0.236078
sodium_si                      0.236051
albumin                        0.235997
hba1c_percent                  0.220075
hdl_cholesterol                0.116106
lymphocyte_percent             0.007083
monocyte_percent               0.007083
neutrophil_percent             0.007083
platelet_count                 0.006028
red_blood_cell_count           0.006001
red_cell_distribution_width    0.006001
mean_corpuscular_volume        0.006001
hematocrit                     0.006001
hemoglobin                     0.006001
white_blood_cell_count         0.006001
age_years                      0.000000
sex                            0.000000
dtype: float64

In [12]:
df.columns

Index(['sex', 'age_years', 'albumin', 'blood_urea_nitrogen', 'creatinine',
       'uric_acid', 'hba1c_percent', 'total_cholesterol', 'hdl_cholesterol',
       'triglycerides', 'white_blood_cell_count', 'lymphocyte_percent',
       'monocyte_percent', 'neutrophil_percent', 'red_blood_cell_count',
       'hemoglobin', 'hematocrit', 'mean_corpuscular_volume',
       'red_cell_distribution_width', 'platelet_count', 'calcium', 'sodium_si',
       'potassium_si', 'phosphorus', 'total_bilirubin', 'total_protein',
       'globulin', 'ggt_si'],
      dtype='str')

In [13]:
all_cols = []
for a in df.columns:
    all_cols.append(a)

In [14]:
len(all_cols)

28

In [15]:
df.columns.tolist()

['sex',
 'age_years',
 'albumin',
 'blood_urea_nitrogen',
 'creatinine',
 'uric_acid',
 'hba1c_percent',
 'total_cholesterol',
 'hdl_cholesterol',
 'triglycerides',
 'white_blood_cell_count',
 'lymphocyte_percent',
 'monocyte_percent',
 'neutrophil_percent',
 'red_blood_cell_count',
 'hemoglobin',
 'hematocrit',
 'mean_corpuscular_volume',
 'red_cell_distribution_width',
 'platelet_count',
 'calcium',
 'sodium_si',
 'potassium_si',
 'phosphorus',
 'total_bilirubin',
 'total_protein',
 'globulin',
 'ggt_si']

In [16]:
df["age_years"].describe()

count    36992.000000
mean        35.686175
std         24.004774
min          1.000000
25%         14.000000
50%         33.000000
75%         56.000000
max         80.000000
Name: age_years, dtype: float64

In [17]:
def helper_fun(df: pd.DataFrame, threshold: float):
    numeric_cols = df.select_dtypes(include="number").columns
    invalid_mask = df[numeric_cols].abs() < threshold

    df[numeric_cols] = df[numeric_cols].mask(invalid_mask)

    return df

In [18]:
missingness_report = pd.read_csv('/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/outputs/reports/missingness_report.csv')

In [19]:
missingness_report.columns

Index(['feature', 'missing_ratio'], dtype='str')

In [20]:
missingness_report.sort_values(by = 'missing_ratio', ascending=False)

                        feature  missing_ratio
0                       calcium       0.379372
1               total_bilirubin       0.379262
2                      globulin       0.378910
3                 total_protein       0.378888
4                  potassium_si       0.378646
5                     uric_acid       0.378558
6             total_cholesterol       0.378514
7                        ggt_si       0.378492
8           blood_urea_nitrogen       0.378470
9                    phosphorus       0.378448
10                triglycerides       0.378404
11                   creatinine       0.378404
12                    sodium_si       0.378382
13                      albumin       0.378338
14                hba1c_percent       0.365382
15              hdl_cholesterol       0.280784
16           lymphocyte_percent       0.192073
17             monocyte_percent       0.192073
18           neutrophil_percent       0.192073
19               platelet_count       0.191215
20         red_blood_cell_count       0.191193
21  red_cell_distribution_width       0.191193
22      mean_corpuscular_volume       0.191193
23                   hematocrit       0.191193
24                   hemoglobin       0.191193
25       white_blood_cell_count       0.191193
26                    age_years       0.038868
27                          sex       0.000000

In [21]:
pip install scikit-learn -q

Note: you may need to restart the kernel to use updated packages.

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from biological_age.preprocessing import preprocess


numeric_pipeline = Pipeline([("imputer", SimpleImputer(strategy="median"),),
                             ("scaler", StandardScaler())])

categorical_pipline = Pipeline([("imputer", SimpleImputer(strategy="most_frequent"))])

In [23]:
def pre_processor():
    preprocessor_cat_num = ColumnTransformer([('numeric', numeric_pipeline, NUMERIC_FEATURES),
                                      ('categorical', categorical_pipline, CATEGORICAL_FEATURES)])

    return preprocessor_cat_num

In [24]:
df['sex']

0        1.0
1        2.0
2        1.0
3        2.0
4        2.0
        ...
36987    2.0
36988    1.0
36989    2.0
36990    1.0
36991    1.0
Name: sex, Length: 36992, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split

def create_split(X, y, t_size = .20,):

    X_train, X_test, y_train, y_test = train_test_split(X, y, t_size, random_state=42)

    return
    (X_train, X_test, Y_train, Y_test)

In [26]:
from sklearn.ensemble import RandomForestRegressor

def train_baseLine_model(preprocessor, X_train, X_test, y_train):

   

    model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1,)

In [27]:
df['age_years'].isna().sum()

np.int64(0)