In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/data/processed/dataset.parquet')

In [3]:
df

,sex,age_years,race_ethnicity,education_level,poverty_income_ratio,albumin,blood_urea_nitrogen,creatinine,uric_acid,fasting_glucose,...,platelet_count,calcium,sodium_si,potassium_si,phosphorus,total_bilirubin,total_protein,globulin,ggt_si,fasting_hours
0,1.0,22.0,3.0,3.0,3.15,4.8,14.0,0.91,4.9,92.0,...,223.0,9.6,137.0,3.9,3.3,0.6,7.6,2.8,14.0,14.0
1,2.0,3.0,1.0,NaN,0.60,NaN,NaN,NaN,NaN,NaN,...,259.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,14.0,6.0,NaN,4.07,4.0,16.0,0.65,5.8,NaN,...,259.0,9.1,137.0,3.8,5.0,0.4,7.0,3.0,8.0,NaN
3,2.0,44.0,3.0,4.0,1.67,3.7,5.0,0.89,4.5,82.0,...,297.0,9.2,138.0,4.3,3.2,0.3,6.0,2.3,18.0,11.0
4,2.0,14.0,4.0,NaN,0.57,4.1,12.0,0.50,5.8,88.0,...,257.0,9.7,139.0,4.0,4.3,0.5,6.9,2.8,20.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43685,1.0,40.0,4.0,5.0,3.82,3.9,9.0,0.98,5.9,NaN,...,203.0,8.8,140.0,3.6,3.1,0.2,7.4,3.5,25.0,NaN
43686,1.0,2.0,4.0,NaN,0.07,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43687,2.0,7.0,3.0,NaN,1.22,NaN,NaN,NaN,NaN,NaN,...,305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43688,1.0,63.0,4.0,2.0,3.71,3.6,13.0,0.93,6.0,125.0,...,194.0,8.6,142.0,3.9,2.4,0.6,6.7,3.1,18.0,NaN
43689,1.0,74.0,2.0,3.0,NaN,3.8,20.0,0.97,5.6,96.0,...,160.0,9.2,145.0,4.3,3.0,0.5,6.9,3.1,20.0,NaN

In [4]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 43690 entries, 0 to 43689
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sex                          43690 non-null  float64
 1   age_years                    42559 non-null  float64
 2   race_ethnicity               43690 non-null  float64
 3   education_level              26114 non-null  float64
 4   poverty_income_ratio         39109 non-null  float64
 5   albumin                      28262 non-null  float64
 6   blood_urea_nitrogen          28256 non-null  float64
 7   creatinine                   28259 non-null  float64
 8   uric_acid                    28252 non-null  float64
 9   fasting_glucose              13921 non-null  float64
 10  hba1c_percent                28851 non-null  float64
 11  fasting_insulin              2881 non-null   float64
 12  total_cholesterol            28254 non-null  float64
 13  hdl_cholesterol              32697 non-null  float64
 14  ldl_cholesterol_si           28039 non-null  float64
 15  triglycerides                28259 non-null  float64
 16  white_blood_cell_count       36770 non-null  float64
 17  lymphocyte_percent           36730 non-null  float64
 18  monocyte_percent             36730 non-null  float64
 19  neutrophil_percent           36730 non-null  float64
 20  red_blood_cell_count         36770 non-null  float64
 21  hemoglobin                   36770 non-null  float64
 22  hematocrit                   36770 non-null  float64
 23  mean_corpuscular_volume      36770 non-null  float64
 24  red_cell_distribution_width  36770 non-null  float64
 25  platelet_count               36769 non-null  float64
 26  calcium                      28215 non-null  float64
 27  sodium_si                    28260 non-null  float64
 28  potassium_si                 28248 non-null  float64
 29  phosphorus                   28257 non-null  float64
 30  total_bilirubin              28220 non-null  float64
 31  total_protein                28237 non-null  float64
 32  globulin                     28236 non-null  float64
 33  ggt_si                       28255 non-null  float64
 34  fasting_hours                6358 non-null   float64
dtypes: float64(35)
memory usage: 11.7 MB

(43690, 35)

In [5]:
df.describe()

,sex,age_years,race_ethnicity,education_level,poverty_income_ratio,albumin,blood_urea_nitrogen,creatinine,uric_acid,fasting_glucose,...,platelet_count,calcium,sodium_si,potassium_si,phosphorus,total_bilirubin,total_protein,globulin,ggt_si,fasting_hours
count,43690.000000,42559.000000,43690.000000,26114.000000,39109.000000,28262.000000,28256.000000,28259.000000,28252.000000,13921.000000,...,36769.000000,28215.000000,28260.000000,28248.000000,28257.000000,28220.000000,28237.000000,28236.000000,28255.000000,6358.000000
mean,1.505905,34.166757,3.368574,3.498889,2.291418,4.234576,13.632963,0.871370,5.346935,108.487609,...,255.917430,9.386454,139.629512,4.016339,3.790550,0.573819,7.167188,2.932660,27.192001,11.180560
std,0.499971,24.353789,1.632333,1.255638,1.596035,0.365526,5.846568,0.452541,1.429128,35.280137,...,69.007234,0.371755,2.450205,0.353310,0.628013,0.308471,0.462675,0.455298,43.167058,3.156669
min,1.000000,1.000000,1.000000,1.000000,0.010000,2.000000,1.000000,0.160000,0.400000,21.000000,...,8.000000,6.400000,102.000000,2.300000,1.000000,0.010000,4.400000,0.600000,2.000000,1.000000
25%,1.000000,12.000000,2.000000,3.000000,0.950000,4.000000,10.000000,0.680000,4.300000,93.000000,...,209.000000,9.100000,138.000000,3.800000,3.400000,0.400000,6.900000,2.600000,13.000000,10.000000
50%,2.000000,31.000000,3.000000,4.000000,1.810000,4.200000,13.000000,0.820000,5.200000,100.000000,...,248.000000,9.400000,140.000000,4.000000,3.800000,0.500000,7.200000,2.900000,18.000000,11.000000
75%,2.000000,55.000000,4.000000,4.000000,3.590000,4.500000,16.000000,0.980000,6.200000,110.000000,...,295.000000,9.600000,141.000000,4.200000,4.200000,0.700000,7.500000,3.200000,28.000000,13.000000
max,2.000000,80.000000,7.000000,9.000000,5.000000,5.600000,96.000000,17.410000,18.000000,524.000000,...,1021.000000,14.800000,161.000000,7.300000,10.900000,7.100000,10.200000,7.000000,2394.000000,36.000000

In [6]:
df.isna().mean().sort_values()

sex                            0.000000
race_ethnicity                 0.000000
age_years                      0.025887
poverty_income_ratio           0.104852
red_cell_distribution_width    0.158389
mean_corpuscular_volume        0.158389
hematocrit                     0.158389
hemoglobin                     0.158389
red_blood_cell_count           0.158389
white_blood_cell_count         0.158389
platelet_count                 0.158412
neutrophil_percent             0.159304
monocyte_percent               0.159304
lymphocyte_percent             0.159304
hdl_cholesterol                0.251614
hba1c_percent                  0.339643
albumin                        0.353124
sodium_si                      0.353170
triglycerides                  0.353193
creatinine                     0.353193
phosphorus                     0.353239
blood_urea_nitrogen            0.353262
ggt_si                         0.353285
total_cholesterol              0.353307
uric_acid                      0.353353
potassium_si                   0.353445
total_protein                  0.353696
globulin                       0.353719
total_bilirubin                0.354086
calcium                        0.354200
ldl_cholesterol_si             0.358228
education_level                0.402289
fasting_glucose                0.681369
fasting_hours                  0.854475
fasting_insulin                0.934058
dtype: float64

In [7]:
df['age_years'].sort_values()

23883    1.0
40280    1.0
4230     1.0
40308    1.0
40331    1.0
        ...
43565    NaN
43567    NaN
43568    NaN
43578    NaN
43600    NaN
Name: age_years, Length: 43690, dtype: float64

In [8]:
df.select_dtypes(include=["object", "string"]).columns

Index([], dtype='str')

In [9]:
numeric_cols = df.select_dtypes(include="number").columns

df[numeric_cols] = df[numeric_cols].mask(
    df[numeric_cols].abs() < 1e-10
)

In [10]:
df["age_years"].describe()

count    42559.000000
mean        34.166757
std         24.353789
min          1.000000
25%         12.000000
50%         31.000000
75%         55.000000
max         80.000000
Name: age_years, dtype: float64

In [11]:
df.isna().mean().sort_values(ascending=False)

fasting_insulin                0.934058
fasting_hours                  0.854475
fasting_glucose                0.681369
education_level                0.402289
ldl_cholesterol_si             0.358228
calcium                        0.354200
total_bilirubin                0.354086
globulin                       0.353719
total_protein                  0.353696
potassium_si                   0.353445
uric_acid                      0.353353
total_cholesterol              0.353307
ggt_si                         0.353285
blood_urea_nitrogen            0.353262
phosphorus                     0.353239
creatinine                     0.353193
triglycerides                  0.353193
sodium_si                      0.353170
albumin                        0.353124
hba1c_percent                  0.339643
hdl_cholesterol                0.251614
lymphocyte_percent             0.159304
neutrophil_percent             0.159304
monocyte_percent               0.159304
platelet_count                 0.158412
hematocrit                     0.158389
mean_corpuscular_volume        0.158389
red_cell_distribution_width    0.158389
hemoglobin                     0.158389
red_blood_cell_count           0.158389
white_blood_cell_count         0.158389
poverty_income_ratio           0.104852
age_years                      0.025887
race_ethnicity                 0.000000
sex                            0.000000
dtype: float64

In [12]:
df.columns

Index(['sex', 'age_years', 'race_ethnicity', 'education_level',
       'poverty_income_ratio', 'albumin', 'blood_urea_nitrogen', 'creatinine',
       'uric_acid', 'fasting_glucose', 'hba1c_percent', 'fasting_insulin',
       'total_cholesterol', 'hdl_cholesterol', 'ldl_cholesterol_si',
       'triglycerides', 'white_blood_cell_count', 'lymphocyte_percent',
       'monocyte_percent', 'neutrophil_percent', 'red_blood_cell_count',
       'hemoglobin', 'hematocrit', 'mean_corpuscular_volume',
       'red_cell_distribution_width', 'platelet_count', 'calcium', 'sodium_si',
       'potassium_si', 'phosphorus', 'total_bilirubin', 'total_protein',
       'globulin', 'ggt_si', 'fasting_hours'],
      dtype='str')

In [13]:
all_cols = []
for a in df.columns:
    all_cols.append(a)

In [14]:
len(all_cols)

35

In [15]:
df.columns.tolist()

['sex',
 'age_years',
 'race_ethnicity',
 'education_level',
 'poverty_income_ratio',
 'albumin',
 'blood_urea_nitrogen',
 'creatinine',
 'uric_acid',
 'fasting_glucose',
 'hba1c_percent',
 'fasting_insulin',
 'total_cholesterol',
 'hdl_cholesterol',
 'ldl_cholesterol_si',
 'triglycerides',
 'white_blood_cell_count',
 'lymphocyte_percent',
 'monocyte_percent',
 'neutrophil_percent',
 'red_blood_cell_count',
 'hemoglobin',
 'hematocrit',
 'mean_corpuscular_volume',
 'red_cell_distribution_width',
 'platelet_count',
 'calcium',
 'sodium_si',
 'potassium_si',
 'phosphorus',
 'total_bilirubin',
 'total_protein',
 'globulin',
 'ggt_si',
 'fasting_hours']

In [16]:
df["age_years"].describe()

count    42559.000000
mean        34.166757
std         24.353789
min          1.000000
25%         12.000000
50%         31.000000
75%         55.000000
max         80.000000
Name: age_years, dtype: float64

In [17]:
def helper_fun(df: pd.DataFrame, threshold: float):
    numeric_cols = df.select_dtypes(include="number").columns
    invalid_mask = df[numeric_cols].abs() < threshold

    df[numeric_cols] = df[numeric_cols].mask(invalid_mask)

    return df

In [18]:
missingness_report = pd.read_csv('/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/outputs/reports/missingness_report.csv')

In [19]:
missingness_report.columns

Index(['feature', 'missing_ratio'], dtype='str')

In [ ]:
missingness_report.sort_values(by = 'missing_ratio', ascending=False)