In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/data/processed/dataset.parquet')

In [3]:
df

,participant_id,survey_cycle,interview_exam_status,sex,age_years,age_months,race_ethnicity_old,race_ethnicity,exam_season,age_at_exam_years,...,years_in_us_grouped,marital_status_grouped,interview_weight_prepandemic,mec_weight_prepandemic,hdl_below_detection_limit,fasting_subsample_weight_prepandemic,nucleated_red_blood_cells,alt_below_detection_limit,ggt_below_detection_limit,bilirubin_below_detection_limit
0,62161.0,7.0,2.0,1.0,22.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62162.0,7.0,2.0,2.0,3.0,NaN,1.0,1.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62163.0,7.0,2.0,1.0,14.0,NaN,5.0,6.0,2.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62164.0,7.0,2.0,2.0,44.0,NaN,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62165.0,7.0,2.0,2.0,14.0,NaN,4.0,4.0,2.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45457,124818.0,66.0,2.0,1.0,40.0,NaN,4.0,4.0,1.0,NaN,...,NaN,1.0,21586.596728,21666.889837,NaN,NaN,0.1,NaN,NaN,NaN
45458,124819.0,66.0,2.0,1.0,2.0,NaN,4.0,4.0,2.0,NaN,...,NaN,NaN,1664.919253,1838.169709,NaN,NaN,NaN,NaN,NaN,NaN
45459,124820.0,66.0,2.0,2.0,7.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,14819.783161,16497.806674,NaN,NaN,0.1,NaN,NaN,NaN
45460,124821.0,66.0,2.0,1.0,63.0,NaN,4.0,4.0,1.0,NaN,...,NaN,2.0,4666.817952,4853.430230,NaN,10704.467871,0.1,NaN,NaN,NaN
45461,124822.0,66.0,2.0,1.0,74.0,NaN,2.0,2.0,2.0,NaN,...,4.0,1.0,14024.476634,15195.796658,NaN,36585.328133,0.2,NaN,NaN,NaN

In [4]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 45462 entries, 0 to 45461
Columns: 128 entries, participant_id to bilirubin_below_detection_limit
dtypes: float64(127), str(1)
memory usage: 44.7 MB

(45462, 128)

In [5]:
df.describe()

,participant_id,survey_cycle,interview_exam_status,sex,age_years,age_months,race_ethnicity_old,race_ethnicity,exam_season,age_at_exam_years,...,years_in_us_grouped,marital_status_grouped,interview_weight_prepandemic,mec_weight_prepandemic,hdl_below_detection_limit,fasting_subsample_weight_prepandemic,nucleated_red_blood_cells,alt_below_detection_limit,ggt_below_detection_limit,bilirubin_below_detection_limit
count,45462.000000,45462.000000,45462.000000,45462.000000,43695.000000,2831.000000,45462.000000,45462.000000,42995.000000,3418.000000,...,3028.000000,9232.000000,15560.000000,14300.000000,1.150000e+02,4476.000000,8163.000000,2.0,1.0,1.0
mean,91505.187035,27.856034,1.945735,1.505697,33.638105,10.991522,3.156856,3.372377,1.501012,9.641311,...,6.701453,1.708622,20714.921079,22540.151888,1.124108e+68,61275.546688,0.122357,1.0,1.0,1.0
std,20068.910994,27.523884,0.226543,0.499973,24.477865,6.756277,1.263701,1.632560,0.500005,5.180846,...,18.534338,2.755878,25323.916482,27547.424277,8.486501e+68,69921.204651,0.088114,0.0,NaN,NaN
min,62161.000000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,...,1.000000,1.000000,1017.784203,1116.245058,-2.938437e+56,4808.069916,0.100000,1.0,1.0,1.0
25%,75166.250000,8.000000,2.000000,1.000000,11.000000,5.000000,2.000000,2.000000,1.000000,5.000000,...,2.000000,1.000000,7435.543058,8024.492120,-2.938385e+56,22500.766893,0.100000,1.0,1.0,1.0
50%,86531.500000,9.000000,2.000000,2.000000,30.000000,10.000000,3.000000,3.000000,2.000000,9.000000,...,3.000000,1.000000,12712.564300,13784.310882,-4.621118e-02,37383.916589,0.100000,1.0,1.0,1.0
75%,113456.750000,66.000000,2.000000,2.000000,55.000000,17.000000,4.000000,4.000000,2.000000,14.000000,...,4.000000,2.000000,22761.140907,24696.454242,-4.905369e-05,69394.587011,0.100000,1.0,1.0,1.0
max,124822.000000,66.000000,2.000000,2.000000,80.000000,24.000000,5.000000,7.000000,2.000000,20.000000,...,99.000000,99.000000,338363.600192,367555.742979,6.463620e+69,741259.188749,3.000000,1.0,1.0,1.0

In [6]:
df.isna().mean().sort_values()

participant_id                     0.000000
survey_cycle                       0.000000
interview_exam_status              0.000000
sex                                0.000000
survey_year                        0.000000
                                     ...
active_duty_status                 0.964344
hdl_below_detection_limit          0.997470
alt_below_detection_limit          0.999956
ggt_below_detection_limit          0.999978
bilirubin_below_detection_limit    0.999978
Length: 128, dtype: float64

In [8]:
df['age_years'].sort_values()

8369     1.0
25006    1.0
15727    1.0
15750    1.0
24972    1.0
        ...
45335    NaN
45346    NaN
45368    NaN
45404    NaN
45439    NaN
Name: age_years, Length: 45462, dtype: float64

In [9]:
df.select_dtypes(include=["object", "string"]).columns

Index(['survey_year'], dtype='str')

In [10]:
numeric_cols = df.select_dtypes(include="number").columns

df[numeric_cols] = df[numeric_cols].mask(
    df[numeric_cols].abs() < 1e-10
)

In [12]:
df["age_years"].describe()

count    43695.000000
mean        33.638105
std         24.477865
min          1.000000
25%         11.000000
50%         30.000000
75%         55.000000
max         80.000000
Name: age_years, dtype: float64

In [13]:
df.isna().mean().sort_values(ascending=False)

bilirubin_below_detection_limit    0.999978
ggt_below_detection_limit          0.999978
alt_below_detection_limit          0.999956
hdl_below_detection_limit          0.997470
active_duty_status                 0.964344
                                     ...
interview_language                 0.000000
interview_interpreter_used         0.000000
survey_year                        0.000000
masked_strata                      0.000000
participant_id                     0.000000
Length: 128, dtype: float64

In [14]:
df.columns

Index(['participant_id', 'survey_cycle', 'interview_exam_status', 'sex',
       'age_years', 'age_months', 'race_ethnicity_old', 'race_ethnicity',
       'exam_season', 'age_at_exam_years',
       ...
       'years_in_us_grouped', 'marital_status_grouped',
       'interview_weight_prepandemic', 'mec_weight_prepandemic',
       'hdl_below_detection_limit', 'fasting_subsample_weight_prepandemic',
       'nucleated_red_blood_cells', 'alt_below_detection_limit',
       'ggt_below_detection_limit', 'bilirubin_below_detection_limit'],
      dtype='str', length=128)

In [15]:
all_cols = []
for a in df.columns:
    all_cols.append(a)

In [16]:
len(all_cols)

128

In [17]:
df.columns.tolist()

['participant_id',
 'survey_cycle',
 'interview_exam_status',
 'sex',
 'age_years',
 'age_months',
 'race_ethnicity_old',
 'race_ethnicity',
 'exam_season',
 'age_at_exam_years',
 'age_at_exam_months',
 'military_status',
 'active_duty_status',
 'country_of_birth',
 'citizenship_status',
 'years_in_us',
 'education_level_youth',
 'education_level',
 'marital_status',
 'pregnancy_status',
 'interview_language',
 'interview_proxy_used',
 'interview_interpreter_used',
 'family_interview_language',
 'family_proxy_used',
 'family_interpreter_used',
 'mec_interview_language',
 'mec_proxy_used',
 'mec_interpreter_used',
 'audio_language',
 'interview_weight_2yr',
 'mec_exam_weight_2yr',
 'masked_psu',
 'masked_strata',
 'household_income',
 'family_income',
 'poverty_income_ratio',
 'household_size',
 'family_size',
 'num_children_0_5',
 'num_children_6_17',
 'num_elderly_60_plus',
 'household_reference_gender',
 'household_reference_age',
 'household_reference_birth_country',
 'household_reference_education',
 'household_reference_marital_status',
 'spouse_education_level',
 'survey_year',
 'albumin',
 'albumin_si',
 'alt_si',
 'ast_si',
 'alkaline_phosphatase_si',
 'blood_urea_nitrogen',
 'blood_urea_nitrogen_si',
 'calcium',
 'calcium_si',
 'creatine_kinase',
 'total_cholesterol',
 'total_cholesterol_si',
 'LBXSC3SI',
 'creatinine',
 'creatinine_si',
 'ggt_si',
 'triglycerides',
 'triglycerides_si',
 'serum_iron',
 'serum_iron_si',
 'ldl_cholesterol_si',
 'phosphorus',
 'phosphorus_si',
 'total_bilirubin',
 'total_bilirubin_si',
 'total_protein',
 'total_protein_si',
 'uric_acid',
 'uric_acid_si',
 'sodium_si',
 'potassium_si',
 'chloride_si',
 'osmolality_si',
 'globulin',
 'globulin_si',
 'triglycerides_alt',
 'triglycerides_alt_si',
 'hba1c_percent',
 'hdl_cholesterol',
 'hdl_cholesterol_si',
 'fasting_subsample_weight',
 'fasting_glucose',
 'fasting_glucose_si',
 'fasting_insulin',
 'fasting_insulin_si',
 'fasting_hours',
 'fasting_minutes',
 'white_blood_cell_count',
 'lymphocyte_percent',
 'monocyte_percent',
 'neutrophil_percent',
 'eosinophil_percent',
 'basophil_percent',
 'lymphocyte_count',
 'monocyte_count',
 'neutrophil_count',
 'eosinophil_count',
 'basophil_count',
 'red_blood_cell_count',
 'hemoglobin',
 'hematocrit',
 'mean_corpuscular_volume',
 'mean_corpuscular_hemoglobin',
 'mean_corpuscular_hgb_concentration',
 'red_cell_distribution_width',
 'platelet_count',
 'mean_platelet_volume',
 'hepatitis_b_antibody_1',
 'hepatitis_b_antibody_2',
 'years_in_us_grouped',
 'marital_status_grouped',
 'interview_weight_prepandemic',
 'mec_weight_prepandemic',
 'hdl_below_detection_limit',
 'fasting_subsample_weight_prepandemic',
 'nucleated_red_blood_cells',
 'alt_below_detection_limit',
 'ggt_below_detection_limit',
 'bilirubin_below_detection_limit']

In [19]:
df["age_years"].describe()

count    43695.000000
mean        33.638105
std         24.477865
min          1.000000
25%         11.000000
50%         30.000000
75%         55.000000
max         80.000000
Name: age_years, dtype: float64

In [20]:
def helper_fun(df: pd.DataFrame, threshold: float):
    numeric_cols = df.select_dtypes(include="number").columns
    invalid_mask = df[numeric_cols].abs() < threshold

    df[numeric_cols] = df[numeric_cols].mask(invalid_mask)

    return df

In [21]:
from biological_age.features.column_mapping import (
    validate_columns,
    rename_columns,
)